name: Abismal builds on macOS (x86)

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Update Homebrew
      run: brew update
    - name: Install automake (autoconf and libtool assumed present)
      run: brew install automake
    - name: Install dependencies
      run: brew install htslib gsl
    - name: Generate configure script
      run: ./autogen.sh
    - name: configure with g++-13
      run: ./configure CXX="g++-13" CPPFLAGS="-I$(brew --prefix)/include" LDFLAGS="-L$(brew --prefix)/lib"
    - name: make
      run: make CXXFLAGS="-O2 -DNDEBUG -Wl,-ld_classic"
    - name: Run tests
      run: make check
    - name: Cleanup after build and test
      run: make distclean
