name: Abismal distribution check on Ubuntu

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Update packages
      run: sudo apt-get update
    - name: Install dependencies
      run: sudo apt-get install -y libhts-dev
    - name: Generate configure script
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make check with two threads
      run: make -j2 check
    - name: make distcheck
      run: make distcheck
